### ISSUE TITLE
File size limitation

### ISSUE THREAD

**Issue by Frank-LSY** [abdelghani-amz/Visualisation-3D-DIAG#1]
Hi,

I'm trying to upload files and visualize but it always keeps prompting an alarm message like
`Fichier volumineux. Veuillez sélectionnez un fichier approprié.` 

It seems the file size limitation is very small, cuz I've already tried files with like 10 MB.

So I'm wondering what's the file size limitation for the upload.  You know the CT scan files could often be very big.

Thanks.

**Comment by abdelghani-amz** [comment]
sorry for the late reply, the code works only with specific masks in nii format, the masks have to be composed of 4 labels ranging from 0 to 3, ill upload a file in the repo for you to try called mask.nii.
if the error still persists, there might be a problem with the version ive uploaded on github, but ive already deployed a production version on this link http://193.194.91.207:5000/  around a year ago so just use the version on the link worst case scenario.

**Comment by Frank-LSY** [comment]
Thanks for the reply! The example file does work for the program. However, I guess it's may due to the "specific masks" you mentioned that I can't get desired results with my own data. 
Anyway, I've found some other repos to further my work. 
The 3D visualization is fabulous! Nice work!

**Comment by abdelghani-amz** [comment]
thank you, im glad you like it, im here if you need any help with adapting my code to your  data. 
Good luck!
